apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextweb-deployment
  namespace: koma-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextweb-deployment
  template:
    metadata:
      name: nextweb-pod
      labels:
        app: nextweb-deployment
    spec:
      containers:
        - name: nextweb
          image: komavideo/deeplearnaws-nextweb:v8
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextweb-nodeport-service
  namespace: koma-dev
spec:
  type: NodePort
  selector:
    # 从标签中选取操作目标
    app: nextweb-deployment
  ports: 
    - name: http
      port: 3000
      targetPort: 3000
      #nodePort: 32020