apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nextweb-rs
  labels:
    app: nextweb
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nextweb
        image: komavideo/deeplearnaws-nextweb:v3