apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextweb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextweb-deployment
  template:
    metadata:
      name: nextweb-pod
      labels:
        app: nextweb-deployment
    spec:
      containers:
        - name: nextweb
          image: komavideo/deeplearnaws-nextweb:v3
          ports:
            - containerPort: 3000
---
# This is for apply in NodePort type
apiVersion: v1
kind: Service
metadata:
  name: nextweb-deployment-service
spec:
  type: NodePort 
  selector: 
    app: nextweb-deployment
  ports: 
    - name: http
      port: 3000
      targetPort: 3000