apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nextweb-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextweb-rs
  template:
    metadata:
      name: nextweb-pod
      labels:
        app: nextweb-rs
    spec:
      containers:
      - name: nextweb
        image: komavideo/deeplearnaws-nextweb:v1
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextweb-rs-nodeport-service
spec:
  type: NodePort
  selector:
    app: nextweb-rs # Map to above metadata:name
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      #nodePort: 32020