apiVersion: v1
kind: Pod
metadata:
  name: nextweb-pod
  labels: 
    app: nextweb
spec:
  initContainers:
    - name: init-mysqldb
      image: busybox:1.35
      command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
  containers:
    - name: nextweb
      image: komavideo/deeplearnaws-nextweb:v8
      env:
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: dbpwd
      ports:
        - containerPort: 3000